services:
  - type: web
    name: helsinki-spots
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      sqlite3 database.db < schema.sql
    startCommand: gunicorn app:app